// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250130170810_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Domain.BankDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankIfscCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardDetailsId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCardDetialsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNetBankingAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NebankingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
